import hashlib
import hmac

import requests
from django.core.cache import cache
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseForbidden,
)

from ..helper import generate_token, generate_token_with_context
from .insta_feed import fetch_fresh_media_url


def _fetch(media_url: str):
    """Fetch media_url. Returns (content, content_type), or (None, None) on
    any failure — callers decide what "failure" means for them."""
    try:
        response = requests.get(media_url, timeout=10)
        response.raise_for_status()
    except requests.exceptions.RequestException:
        return None, None
    return response.content, response.headers.get(
        "Content-Type", "application/octet-stream"
    )


def resolve_media_url(request: HttpRequest):
    provided_hash = request.GET.get("hash")
    # Django decodes the query parameter once, restoring the original URL that
    # replace_media_urls encoded with urllib.parse.quote(value, safe="").
    # No further unquoting is needed or correct.
    media_url = request.GET.get("url")
    # Present only on links generated by replace_media_urls_for_posts() —
    # older/plain links (generate_token(url) alone) have none of these, and
    # are verified and served exactly as before.
    post_id = request.GET.get("post_id", "")
    child_id = request.GET.get("child_id", "")
    account = request.GET.get("account", "")

    if not provided_hash or not media_url:
        return HttpResponseBadRequest("Missing required parameters.")

    if post_id:
        expected_hash = generate_token_with_context(
            media_url, post_id, child_id, account
        )
    else:
        expected_hash = generate_token(media_url)

    if not hmac.compare_digest(provided_hash, expected_hash):
        return HttpResponseForbidden("Invalid token.")

    cache_key = (
        "resolve_media_url:"
        + hashlib.sha256(request.get_full_path().encode()).hexdigest()
    )
    cached = cache.get(cache_key)
    if cached:
        return HttpResponse(cached["content"], content_type=cached["content_type"])

    content, content_type = _fetch(media_url)

    if content is None and post_id:
        # The embedded signed URL may already be expired even though our own
        # cache entry for it is not — see generate_token_with_context()'s
        # docstring. Re-fetch this one post/child from Instagram and retry
        # once before giving up.
        fresh_url = fetch_fresh_media_url(post_id, child_id, account)
        if fresh_url:
            content, content_type = _fetch(fresh_url)

    if content is None:
        return HttpResponseBadRequest("Failed to fetch media URL.")

    cache.set(
        cache_key,
        {"content": content, "content_type": content_type},
        60 * 60 * 24 * 7,
    )
    return HttpResponse(content, content_type=content_type)
