# Generated by Django 3.2.12 on 2022-11-27 18:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FakeReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("description", models.TextField(default=None)),
                ("url", models.URLField(default=None)),
                ("more_info", models.TextField(default=None)),
            ],
        ),
    ]
