# Generated by Django 3.2.12 on 2023-04-29 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportFake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fakereport",
            name="post_id",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
