# Generated by Django 4.2 on 2023-08-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportFake", "0002_fakereport_post_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="fakereport",
            name="allowed_public",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
