# Generated by Django 4.2 on 2023-08-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportFake", "0003_fakereport_allowed_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="fakereport",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
