# Generated by Django 5.1 on 2024-09-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportFake", "0004_fakereport_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="fakereport",
            name="token",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
