# Generated by Django 5.2.1 on 2025-05-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reportFake", "0005_fakereport_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fakereport",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
