# Generated by Django 6.0.6 on 2026-07-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportFake', '0006_alter_fakereport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fakereport',
            name='posted_to_asana',
            field=models.BooleanField(default=False),
        ),
    ]
