# Generated by Django 6.0.6 on 2026-07-06 07:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('report_fake', 'Fake melden'), ('app_feedback', 'App-Feedback'), ('other', 'Sonstiges')], max_length=20)),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('app_variant', models.CharField(blank=True, default='', max_length=100)),
                ('app_version', models.CharField(blank=True, default='', max_length=50)),
                ('platform', models.CharField(blank=True, default='', max_length=50)),
                ('dedupe_hash', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
