# Generated by Django 6.0.6 on 2026-07-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactrequest",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
    ]
