# Generated by Django 3.2.12 on 2022-11-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expo_token", models.CharField(max_length=256, unique=True)),
                ("notification_new_post", models.BooleanField(default=True)),
            ],
        ),
    ]
