# Generated by Django 3.2.12 on 2023-01-09 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notificationdevice_notification_new_fact_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushMessageLog",
            fields=[
                ("body", models.CharField(max_length=256)),
                ("title", models.CharField(max_length=256)),
                ("data", models.JSONField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("checked", models.BooleanField(default=False)),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="notifications.notificationdevice",
                    ),
                ),
            ],
        ),
    ]
