# Generated by Django 3.2.12 on 2023-01-14 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_pushmessagelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdevice",
            name="date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
