# Generated by Django 6.0.6 on 2026-06-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationdevice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationdevice',
            name='notification_new_pruefpunkt',
            field=models.BooleanField(default=False),
        ),
    ]
