# Generated by Django 6.1.1 on 2026-10-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_notificationdevice_notification_new_pruefpunkt"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdevice",
            name="app_build",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="notificationdevice",
            name="platform",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=50
            ),
        ),
    ]
