# Generated by Django 6.1.2 on 2026-10-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0006_notificationdevice_platform_app_build"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationdevice",
            name="last_seen",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
